### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Svenmax** [pedoc/chinese-dos-games#1]
你好，这个软件我试了试，无法正常下载游戏文件，请问您当时怎么解决的。谢谢

**Comment by Svenmax** [comment]
https://wolfavenue.lanzoux.com/iWG65kdkh9e

有相同问题的朋友请使用这个

**Comment by pedoc** [comment]
未能重现
![image](https://user-images.githubusercontent.com/6604230/120584252-303bda00-c462-11eb-80fc-448e36bbae3a.png)
